### PR TITLE
Bridge IPC

### PR DESCRIPTION
**Pull request by zrock-dev**
# NO US Related

### What did I do?
Merged bridge with console

### How did I do it?
Updated workspace.dsl and uml/frontend-software-system/ files

### Why did I do it?
console was conceived to handle the low-level logic of the bridge. This design was meant to fix low-level bugs without having to rebuild the game. The new design keeps this behavior if the game is compiled without the bridge dependency.

Using console as a middle-man between bridge and screen meant an extra layer of control, but the price is the complexity of implementation and maintainability.

It is not cost effective to use a JNI given that there aren't performance-critical operations to perform by the bridge.

console was removed for the following reasons:
- performance 
marshaling/unmarshaling between console and bridge and then repeat the same operations between console and screen.
- complexity 
an independent socket server running alongside the game and screen to enable their communication. This means console and socket server would need an agreement regarding frames.
- reliability 
On each tick of the game loop, bridge would call console's routines to fetch and bring frames to the screen. 60 frames per second at the minimum.

The new implemented design
- removes extra marshaling/unmarshaling operation,
- reduces the complexity because the socket server and client
and present inside the bridge;
- improves reliability by allowing the bridge communicate directly
with screen.

## Type of Change
- [ ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist
- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [x] No existing features have been broken without good reason.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Screenshots
Level 4, bridge view
package

console's components merged into bridge
image

### CODE REVIEW

**Comment by zrock-dev** [comment]
## Input events propagation problem
Please keep in mind that this new design introduces a problem with the handling of input events at the bridge. Once the server socket receives a stream of events, how will they be propagated to the game?

One approach would be to introduce a producer-consumer,  using a LIFO queue as a buffer to enable the processing of input events per `Game` tick.

## Example
implemented on [task-xx/events-propagation](https://github.com/Pending-Name-21/arquitecture/tree/task-xx/events-propagation) branch.


image
In this example, `Receiver` would be the producer and `AEventBuffer` the consumer.

**Comment by zrock-dev** [comment]
# Impact
## Refactor
[Task 141 | Client socket for console](https://tree.taiga.io/project/joseluis-teran-coffeetime/task/141?)
[Task 144 | server socket for misc](https://tree.taiga.io/project/joseluis-teran-coffeetime/task/144)

## Update
[US:  176 Execution Script](https://tree.taiga.io/project/joseluis-teran-coffeetime/us/176?milestone=395911)

**Comment by zrock-dev** [comment]
package 2e1843b6

**Comment by zrock-dev** [comment]
I've pushed the commits with the solution for the problem

**Review by fabianromeroclaros — APPROVED** [review]

**Review by teran-joseluis — APPROVED** [review]

**Review by luis-espinoza-jalafund — APPROVED** [review]

**Pull request merged**
