### PR TITLE
Render handler refactor

### PR DESCRIPTION
**Pull request by zrock-dev**
# Task-138 | implementation of output intermediate
https://tree.taiga.io/project/joseluis-teran-coffeetime/task/138

#### What did I do?
Refactored render handler, removing the JNI approach.

#### How did I do it?
 Added path attributes to piece classifiers
- 	They're a realization of IFile so they should have the path attribute
- 	available.

Factory and repository interface segregation
- 	Applied inteface segregation on the Factories such as SpriteFactory and
- 	SoundFactory, and with repositories. This is because they had repeated code.

sprite implementation
- 	Removed JNI logic from older version.
- 	Changed relationships to be more clear.

Sound management
- 	The older version used native methods to handle certain operations. But
- 	since bridge has its own IPC it has to be updated.
- 	 Changed SoundPlayer to Repository because that class has a collection of
- 	 Sounds to be queried.
- 	Updated Factory to create a sound based on a given path.
- 	Changed Sound from abstract to concrete, no one would inherit Sound.

changed frame to be a collection
- 	This is because Frame had only a Sprite and a Sound, but a game frame has more than one
- 	of those.

remove sound from Sprite
- 	A Sprite is only the representation of an image. A Sprite with Sound should be achieved through composition.
- 	Removed Sprite logic from SoundPlayer.

#### Why did I do it?
To follow latest architecture update #17 

## Type of Change

- [ ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist
- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [x] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests pass

## Screenshot
image

### CODE REVIEW

**Comment by zrock-dev** [comment]
I think this design refactor can be implemented on
https://github.com/Pending-Name-21/frontend-library/pull/21

**Review by fabianromeroclaros — APPROVED** [review]

**Review by jhael-arce-jalafund — APPROVED** [review]

**Comment by zrock-dev** [comment]
I've added Path validation

**Comment by zrock-dev** [comment]
Updated Sprite and Sound creation design

image

**Review by fabianromeroclaros — APPROVED** [review]

**Review by jhael-arce-jalafund — APPROVED** [review]

**Review by sebastian-barra-jalafund — APPROVED** [review]
well done,

**Pull request merged**
